[package]
name = "async-mongodb-session"
version = "3.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yoshuawuyts/async-mongodb-session"
documentation = "https://docs.rs/async-mongodb-session"
description = "An async-session implementation for MongoDB"
readme = "README.md"
edition = "2021"
keywords = ["tide", "web", "async", "session", "mongodb"]
categories = [
  "network-programming",
  "asynchronous",
  "web-programming::http-server",
]
authors = [
  "Yoshua Wuyts <yoshuawuyts@gmail.com>",
  "Irina Shestak <shestak.irina@gmail.com>",
  "Anton Whalley <anton@venshare.com>",
  "Javier Viola <pepoviola@gmail.com>",
  "Aaron Erhardt <aaron.erhardt@t-online.de>",
]

[features]
default = ["async-std-runtime"]
async-std-runtime = ["mongodb/async-std-runtime"]
tokio-runtime = ["mongodb/tokio-runtime"]

[dependencies]
#async-session = "3"
# using a version without chrono crate
async-session ={git = "https://github.com/http-rs/async-session.git", rev =  "1d1e718264180aa4af49b5c1b75c8c78897687e7"}
mongodb = { package = "mongodb", version = "2.3", default-features = false, features = [
  "bson-chrono-0_4",
] }

[dev-dependencies]
async-std = { version = "1.12", features = ["attributes"] }
lazy_static = "1.4"
rand = "0.8.5"
tokio = { version = "1.20", features = ["rt"] }
