[package]
name = "tide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-mongodb-session = { path = "../../" }
tide = "0.17.0-beta.1"
async-std = "1.10"
